# coding=utf-8
DEFAULT_INITIAL_STAKE = 1
DEFAULT_INITIAL_CASH = 500
DEFAULT_MAX_ROUNDS = 500
DEFAULT_NUMBER_OF_RUNS = 10
DEFAULT_ROULETTE_TYPE = 'AMERICAN'

AMERICAN_POSSIBLE_VALUES = 38
FRENCH_POSSIBLE_VALUES = 37
